import { useState } from 'react'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { Theme } from '../types'
import { presets } from '../presets'
import { generateSkinXml, generateStyleQss } from '../generateSkin'
import { parseSkinZip, parseSkinFiles, type ImportResult } from '../parseSkin'
import { ImportDialog } from './ImportDialog'
import { useI18n } from '../i18n/context'
import type { Lang } from '../i18n/translations'

interface Props {
  theme: Theme
  onLoadPreset: (colors: Theme['colors'], settings?: Theme['settings']) => void
  onImport: (theme: Theme) => void
}

export function Toolbar({ theme, onLoadPreset, onImport }: Props) {
  const { t, lang, setLang } = useI18n()
  const [importResult, setImportResult] = useState<ImportResult | null>(null)
  const [importing, setImporting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleExport() {
    const zip = new JSZip()
    const folder = zip.folder(theme.meta.name || 'MySkin')!
    folder.file('skin.xml', generateSkinXml(theme))
    folder.file('style.qss', generateStyleQss(theme))
    folder.file('README.txt', [
      `${theme.meta.name} - Mixxx Skin`,
      `Author: ${theme.meta.author}`,
      `Description: ${theme.meta.description}`,
      '',
      'Installation:',
      '  1. Extract this folder to your Mixxx skins directory:',
      '     • Linux:   ~/.mixxx/skins/',
      '     • macOS:   ~/Library/Containers/org.mixxx.mixxx/Data/Library/Application Support/Mixxx/skins/',
      '     • Windows: %LOCALAPPDATA%\\Mixxx\\skins\\',
      '  2. Restart Mixxx',
      '  3. Go to Preferences > Interface and select your skin',
      '',
      'Generated by Mixxx Themer',
    ].join('\n'))
    const blob = await zip.generateAsync({ type: 'blob' })
    saveAs(blob, `${theme.meta.name || 'MySkin'}.zip`)
  }

  async function handleImportSkin(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    e.target.value = ''
    setImporting(true)
    setError(null)
    try {
      const result = file.name.endsWith('.zip')
        ? await parseSkinZip(file)
        : await parseSkinFiles(await file.text(), null)
      setImportResult(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Import failed.')
    } finally {
      setImporting(false)
    }
  }

  async function handleImportFiles(e: React.ChangeEvent<HTMLInputElement>) {
    const files = Array.from(e.target.files ?? [])
    if (files.length === 0) return
    e.target.value = ''
    setImporting(true)
    setError(null)
    try {
      const xmlFile = files.find(f => f.name.toLowerCase() === 'skin.xml')
      const qssFile = files.find(f => f.name.toLowerCase().endsWith('.qss'))
      if (!xmlFile) throw new Error(t.noSkinXml)
      const xml = await xmlFile.text()
      const qss = qssFile ? await qssFile.text() : null
      const result = await parseSkinFiles(xml, qss)
      setImportResult(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Import failed.')
    } finally {
      setImporting(false)
    }
  }

  function handleImportConfirm() {
    if (!importResult) return
    onImport(importResult.theme)
    setImportResult(null)
  }

  function handleSaveJson() {
    const blob = new Blob([JSON.stringify(theme, null, 2)], { type: 'application/json' })
    saveAs(blob, `${theme.meta.name || 'MySkin'}.json`)
  }

  function handleLoadJson(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = ev => {
      try {
        const json = JSON.parse(ev.target?.result as string)
        if (json.colors) onLoadPreset(json.colors)
      } catch {
        setError(t.invalidJson)
      }
    }
    reader.readAsText(file)
    e.target.value = ''
  }

  return (
    <>
      {importResult && (
        <ImportDialog result={importResult} onClose={handleImportConfirm} />
      )}

      <div
        className="flex items-center gap-2 px-4 py-2 border-b border-white/10 flex-wrap"
        style={{ backgroundColor: '#0d0d0d' }}
      >
        {/* Presets */}
        <div className="flex items-center gap-1">
          <span className="text-xs text-gray-500 mr-1">{t.presets} :</span>
          {presets.map(p => (
            <button
              key={p.name}
              onClick={() => onLoadPreset(p.colors, p.settings)}
              className="px-2 py-1 text-xs rounded border border-white/10 text-gray-300 hover:bg-white/10 transition-colors"
            >
              {p.name}
            </button>
          ))}
        </div>

        <div className="flex-1" />

        {/* Error */}
        {error && (
          <span className="text-xs text-red-400 px-2">{error}</span>
        )}

        {/* Language toggle */}
        <div className="flex rounded overflow-hidden border border-white/15">
          {(['en', 'fr'] as Lang[]).map(l => (
            <button
              key={l}
              onClick={() => setLang(l)}
              className="px-2.5 py-1 text-xs font-bold uppercase transition-colors"
              style={{
                backgroundColor: lang === l ? '#ffffff22' : 'transparent',
                color: lang === l ? '#ffffff' : '#666',
              }}
            >
              {l}
            </button>
          ))}
        </div>

        <div className="w-px h-4 bg-white/10" />

        {/* Import Mixxx Skin */}
        <div className="flex items-center gap-1">
          {importing && <span className="text-xs text-gray-500">{t.importingLabel}</span>}
          <label
            className="px-3 py-1.5 text-xs rounded border border-blue-500/50 text-blue-300 hover:bg-blue-500/10 transition-colors cursor-pointer font-medium"
            title="Select a .zip of a Mixxx skin"
          >
            {importing ? '…' : t.importSkinZip}
            <input type="file" accept=".zip" className="hidden" onChange={handleImportSkin} />
          </label>
          <label
            className="px-3 py-1.5 text-xs rounded border border-blue-500/30 text-blue-400 hover:bg-blue-500/10 transition-colors cursor-pointer"
            title="Select skin.xml and optionally style.qss directly"
          >
            skin.xml
            <input type="file" accept=".xml,.qss" multiple className="hidden" onChange={handleImportFiles} />
          </label>
        </div>

        <div className="w-px h-4 bg-white/10" />

        {/* Save / Load JSON */}
        <button
          onClick={handleSaveJson}
          className="px-3 py-1.5 text-xs rounded border border-white/20 text-gray-300 hover:bg-white/10 transition-colors"
        >
          {t.saveJson}
        </button>
        <label className="px-3 py-1.5 text-xs rounded border border-white/20 text-gray-300 hover:bg-white/10 transition-colors cursor-pointer">
          {t.loadJson}
          <input type="file" accept=".json" className="hidden" onChange={handleLoadJson} />
        </label>

        {/* Export skin */}
        <button
          onClick={handleExport}
          className="px-4 py-1.5 text-xs rounded font-semibold text-white transition-colors"
          style={{ backgroundColor: '#e94560' }}
        >
          {t.exportSkin}
        </button>
      </div>
    </>
  )
}
