import type { Theme } from './types'

export function generateSkinXml(theme: Theme): string {
  const { meta, colors } = theme
  return `<?xml version="1.0" encoding="utf-8"?>
<skin>
  <manifest>
    <title>${esc(meta.name)}</title>
    <author>${esc(meta.author)}</author>
    <description>${esc(meta.description)}</description>
    <license>${esc(meta.license)}</license>
    <version>1.0.0</version>
    <mixxxVersion>2.4+</mixxxVersion>
    <attribute name="UseColorSchemes" value="false"/>
  </manifest>

  <Style src="style.qss"/>

  <Children>
    <SetVariable name="SignalRGBLowColor">${colors.waveformLow}</SetVariable>
    <SetVariable name="SignalRGBMidColor">${colors.waveformMid}</SetVariable>
    <SetVariable name="SignalRGBHighColor">${colors.waveformHigh}</SetVariable>
    <SetVariable name="PlayedOverlayColor">${colors.waveformPreview}</SetVariable>
    <SetVariable name="EndOfTrackColor">${colors.colorEndOfTrack}</SetVariable>
    <SetVariable name="SignalColor_12">${colors.accentDeck1}</SetVariable>
    <SetVariable name="SignalBgColor_12">${colors.bgDeck1}</SetVariable>
    <SetVariable name="SignalColor_34">${colors.accentDeck2}</SetVariable>
    <SetVariable name="SignalBgColor_34">${colors.bgDeck2}</SetVariable>
    <SetVariable name="SignalColor">${colors.waveformMid}</SetVariable>
  </Children>

</skin>
`
}

export function generateStyleQss(theme: Theme): string {
  const { colors: c, settings: s } = theme
  const br = (n: number) => `${n}px`

  return `/* Generated by Mixxx Themer — ${theme.meta.name} */

/* ─── Base / window ──────────────────────────────────────────────────── */
QWidget,
WWidget {
  background-color: ${c.bgBase};
  color: ${c.textPrimary};
  font-family: ${s.fontFamily};
  font-size: ${s.fontSizeBase}px;
}

#Mixxx,
#SkinContainer {
  background-color: ${c.bgBase};
}

/* ─── Panels / elevated groups ───────────────────────────────────────── */
WWidgetGroup {
  background-color: ${c.bgSurface};
  border-radius: ${br(s.panelBorderRadius)};
}

#TopBar,
#DeckContainer,
#Library_Singleton,
#LibraryContainer {
  background-color: ${c.bgBase};
}

/* ─── Track info ──────────────────────────────────────────────────────── */
WTrackProperty,
WLabel#TrackTitle,
WLabel#TrackTitleMini {
  color: ${c.textPrimary};
  font-size: ${s.fontSizeBase + 1}px;
  font-weight: bold;
}

WLabel#TrackArtist,
WLabel#TrackBy,
WLabel#TrackComment,
WLabel#Duration {
  color: ${c.textSecondary};
  font-size: ${s.fontSizeBase}px;
}

WLabel,
WNumber,
WNumberPos,
WTime,
WRecordingDuration,
WKey {
  color: ${c.textPrimary};
}

/* ─── Buttons ────────────────────────────────────────────────────────── */
WPushButton {
  background-color: ${c.buttonBg};
  color: ${c.buttonText};
  border: 1px solid ${c.borderColor};
  border-radius: ${br(s.buttonBorderRadius)};
  font-weight: bold;
}

WPushButton:hover {
  border: 1px solid ${c.hoverBorder};
}

WPushButton[displayValue="1"],
WPushButton:checked {
  background-color: ${c.buttonBgActive};
  color: ${c.buttonTextActive};
  border: 1px solid ${c.borderColor};
}

WPushButton[displayValue="1"]:hover,
WPushButton:checked:hover {
  border: 1px solid ${c.hoverBorder};
}

/* ─── Play / Cue / Transport ─────────────────────────────────────────── */
#PlayCue[displayValue="1"],
#PlayIndicator[value="1"],
#LoopIndicator {
  background-color: ${c.colorPlay};
  border: 1px solid ${c.colorPlay};
}

#PlayCue[displayValue="0"]:hover,
#CueButton[displayValue="0"]:hover,
#HotcueButton[displayValue="0"]:hover {
  border: 1px solid ${c.hoverBorder};
}

#HotCues_Sampler_Preview {
  background-color: ${c.bgDeep};
}

#HotcueButton,
#CueButton,
#SpecialCueButton {
  font-size: ${s.fontSizeBase + 2}px;
  font-weight: bold;
}

#HotcueButton[displayValue="0"],
#CueButton[displayValue="0"],
#SpecialCueButton[displayValue="0"],
#CueUnderlay,
#PlayIndicator[value="0"] {
  color: ${c.buttonText};
  background-color: ${c.buttonBg};
}

#HotcueButton[displayValue="1"],
#CueButton[displayValue="1"],
#SpecialCueButton[displayValue="1"],
#CueUnderlay[displayValue="1"] {
  color: ${c.buttonTextActive};
  background-color: ${c.colorCue};
}

#HotcueButton[displayValue="1"]:hover,
#CueButton[displayValue="1"]:hover {
  border: 1px solid ${c.hoverBorder};
}

/* ─── Sync / Loop / active borders ──────────────────────────────────── */
#SyncButtonOverlay[displayValue="1"],
#SamplerSyncButton[displayValue="1"] {
  background-color: ${c.colorSync};
  color: ${c.bgDeep};
  font-weight: bold;
}

#LoopSizeButton[displayValue="1"],
#LoopActivateButton[displayValue="1"],
#ReloopButton[displayValue="1"] {
  background-color: ${c.colorSync};
  border: 1px solid ${c.colorSync};
}

#LoopBeatJumpButton,
#LoopSizeButton,
#LoopBeatJumpContainer {
  background-color: ${c.bgBase};
}

#LoopBeatJumpButton:hover,
#LoopSizeButton:hover {
  border: 1px solid ${c.hoverBorder};
}

/* ─── Keylock / rate controls ────────────────────────────────────────── */
#Keylock[displayValue="1"] {
  background-color: ${c.colorSync};
  color: ${c.bgDeep};
  border-radius: ${br(s.buttonBorderRadius)};
}

/* ─── Recording / broadcast ──────────────────────────────────────────── */
#RecordingButton[displayValue="1"] {
  background-color: ${c.colorRecord};
  color: #ffffff;
}

#BroadcastButton[displayValue="1"] {
  background-color: ${c.colorRecord};
  color: #ffffff;
}

/* ─── Knobs ──────────────────────────────────────────────────────────── */
WKnob {
  background-color: ${c.knobBg};
}

/* ─── Sliders ────────────────────────────────────────────────────────── */
WSliderComposed {
  background-color: ${c.bgSurface};
}

/* ─── Waveforms ──────────────────────────────────────────────────────── */
WWaveform,
#DeckOverview,
WOverview {
  background-color: ${c.waveformBg};
}

#DeckOverviewRow1, #DeckOverviewRow2 {
  background-color: ${c.bgDeep};
}

/* ─── VU meters ──────────────────────────────────────────────────────── */
#VUMeterFloating {
  background-color: ${c.bgElevated};
  border-radius: ${br(s.panelBorderRadius + 1)};
}

#VuMeterClippingBorder[highlight="1"] {
  border: 1px solid ${c.colorRecord};
}

/* ─── Spinny ──────────────────────────────────────────────────────────── */
WSpinny,
#SpinnyCover {
  background-color: ${c.spinny};
}

/* ─── Mixer ───────────────────────────────────────────────────────────── */
#Mixer,
#CrossfaderContainer {
  background-color: ${c.bgElevated};
}

/* ─── Library ─────────────────────────────────────────────────────────── */
WTrackTableView,
WLibraryTextBrowser,
WLibrarySidebar {
  background-color: ${c.libraryBg};
  alternate-background-color: ${c.libraryAltBg};
  color: ${c.libraryText};
  selection-background-color: ${c.librarySelectedBg};
  selection-color: ${c.librarySelectedText};
  border: 2px solid ${c.borderColor};
}

WTrackTableView::item:selected,
#LibraryBPMButton::item:selected {
  background-color: ${c.librarySelectedBg};
}

WTrackTableView::item:!selected:focus {
  background-color: ${c.libraryAltBg};
  outline: 1px solid ${c.librarySelectedText};
}

WTrackTableView,
WTrackTableView QCheckBox:focus {
  outline: 1px solid ${c.focusBorder};
}

WTrackTableView:focus,
WLibrarySidebar:focus,
WSearchLineEdit:focus {
  border-color: ${c.focusBorder};
}

WLibrarySidebar {
  border-width: 1px 1px 1px 0px;
  border-style: solid;
  border-color: ${c.borderColor};
}

WLibrarySidebar::item:selected {
  background-color: ${c.librarySidebarSelectedBg};
  color: ${c.textPrimary};
}

/* ─── Scrollbars ─────────────────────────────────────────────────────── */
QScrollBar:vertical, QScrollBar:horizontal {
  background-color: ${c.bgDeep};
  width: 8px;
  height: 8px;
}

QScrollBar::handle:vertical,
QScrollBar::handle:horizontal {
  background-color: ${c.borderColor};
  border-radius: 4px;
}

QScrollBar::handle:vertical:hover,
QScrollBar::handle:horizontal:hover {
  background-color: ${c.hoverBorder};
}

QScrollBar::add-line, QScrollBar::sub-line,
QScrollBar::add-page, QScrollBar::sub-page {
  background: none;
  border: none;
}

/* ─── Input / search fields ──────────────────────────────────────────── */
WSearchLineEdit,
QLineEdit,
QPlainTextEdit,
WBeatSpinBox,
#spinBoxTransition {
  background-color: ${c.inputBg};
  color: ${c.inputText};
  border: 1px solid ${c.inputBorder};
  border-radius: ${br(s.buttonBorderRadius)};
  selection-background-color: ${c.librarySelectedBg};
  selection-color: ${c.librarySelectedText};
}

WSearchLineEdit:hover,
QLineEdit:hover,
WBeatSpinBox:hover {
  border-color: ${c.hoverBorder};
}

WSearchLineEdit:focus,
QLineEdit:focus,
WBeatSpinBox:focus {
  border-color: ${c.focusBorder};
}

/* ─── Tooltips / menus ───────────────────────────────────────────────── */
QToolTip,
WCueMenuPopup,
WTrackMenu,
WTrackMenu QMenu {
  background-color: ${c.bgElevated};
  color: ${c.textPrimary};
  border: 1px solid ${c.borderColor};
}

QMenu::item:selected {
  background-color: ${c.librarySelectedBg};
  color: ${c.librarySelectedText};
}

/* ─── Library feature controls / sidebar buttons ────────────────────── */
#LibraryFeatureControls QPushButton {
  background-color: ${c.buttonBg};
  color: ${c.buttonText};
  border: none;
  border-radius: ${br(s.buttonBorderRadius)};
}

#LibraryFeatureControls QPushButton:hover {
  background-color: ${c.bgElevated};
}

/* ─── Effects ─────────────────────────────────────────────────────────── */
#FxUnitLabel {
  font-size: ${s.fontSizeBase + 2}px;
  font-weight: bold;
  color: ${c.textMuted};
}

/* ─── AutoDJ ──────────────────────────────────────────────────────────── */
#AutoDJContainer {
  background-color: ${c.bgSurface};
}

/* ─── Track table header ─────────────────────────────────────────────── */
WTrackTableViewHeader,
WTrackTableViewHeader::section {
  background-color: ${c.bgSurface};
  color: ${c.textSecondary};
  border: none;
  border-bottom: 1px solid ${c.borderColor};
  font-weight: bold;
}

/* ─── Spacers (Tango-style named spacers) ────────────────────────────── */
#Spacer0f, #RoundSpacer0f { background-color: ${c.bgDeep}; border-radius: ${br(s.panelBorderRadius)}; }
#Spacer1e { background-color: ${c.bgBase}; }
#Spacer25 { background-color: ${c.bgElevated}; }
#Spacer33 { background-color: ${c.bgSurface}; }
`
}

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
